# Place a copy of this config to ~/.aerospace.toml. After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# For the tiles of available commands see: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# For the tiles of available commands see: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md
after-startup-command = []

# Visual indent makes it easier to understand that containers of the same orientation are nested.
# If you have 'auto-opposite-orientation-for-nested-containers' enabled then there is no way to observe the indent
indent-for-nested-containers-with-the-same-orientation = 30

# Start AeroSpace at login
start-at-login = true

# Normalization. See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#layouts
# The 'accordion-padding' specifies the size of the padding. You can set 0 to disable the padding feature
accordion-padding = 30

# Layout of root containers of non-empty workspaces. The layout is applied only on startup
# Possible values: smart|tiles|accordion
# - 'tiles' and 'accordion' are self-describing
# - 'smart' means some "smart logic". Currently, 3 and less windows will get 'tiles' layout,
#   4 and more will get 'accordion' layout. 'smart' can change its behavior in future versions
non-empty-workspaces-root-containers-layout-on-startup = 'smart'

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide display (anything wider than high) gets horizontal orientation,
#               tall display (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#assign-workspaces-to-monitors
# [workspace-to-monitor-force-assignment]
[workspace-to-monitor-force-assignment]
0 = 'secondary'
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'

# It's a declaration of 'main' binding mode. See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#bindings-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# For all possible keys and modifiers see: https://github.com/nikitabobko/AeroSpace/blob/main/src/config/keysMap.swift
# For all possible commands see: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md

# App launching
# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#exec-and-forget
alt-t = 'exec-and-forget open -a wezterm'
alt-b = 'exec-and-forget open -a /Applications/Arc.app/Contents/MacOS/Arc'
alt-n = 'exec-and-forget open -a /Applications/Logseq.app/Contents/MacOS/Logseq'
alt-c = 'exec-and-forget open -a /System/Applications/Calendar.app/Contents/MacOS/Calendar'
alt-shift-c = 'exec-and-forget open -a /Applications/OBS.app/Contents/MacOS/OBS --args --startvirtualcam'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#move-through
alt-shift-h = 'move-through left'
alt-shift-j = 'move-through down'
alt-shift-k = 'move-through up'
alt-shift-l = 'move-through right'

# Fullscreen the focused window
# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#fullscreen
alt-ctrl-f = 'fullscreen'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#workspace
alt-0 = 'workspace 0'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
# alt-5 = 'workspace 5'
# alt-6 = 'workspace 6'
# alt-7 = 'workspace 7'
# alt-8 = 'workspace 8'
# alt-9 = 'workspace 9'
# alt-a = 'workspace A'
# alt-b = 'workspace B'
# alt-c = 'workspace C'
# alt-d = 'workspace D'
# alt-e = 'workspace E'
# alt-f = 'workspace F'
# alt-g = 'workspace G'
# alt-i = 'workspace I'
# alt-m = 'workspace M'
# alt-n = 'workspace N'
# alt-o = 'workspace O'
# alt-p = 'workspace P'
# alt-q = 'workspace Q'
# alt-r = 'workspace R'
# alt-s = 'workspace S'
# alt-t = 'workspace T'
# alt-u = 'workspace U'
# alt-v = 'workspace V'
# alt-w = 'workspace W'
# alt-x = 'workspace X'
# alt-y = 'workspace Y'
# alt-z = 'workspace Z'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#move-node-to-workspace
alt-shift-0 = 'move-node-to-workspace 0'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
# alt-shift-5 = 'move-node-to-workspace 5'
# alt-shift-6 = 'move-node-to-workspace 6'
# alt-shift-7 = 'move-node-to-workspace 7'
# alt-shift-8 = 'move-node-to-workspace 8'
# alt-shift-9 = 'move-node-to-workspace 9'
# alt-shift-a = 'move-node-to-workspace A'
# alt-shift-b = 'move-node-to-workspace B'
# alt-shift-c = 'move-node-to-workspace C'
# alt-shift-d = 'move-node-to-workspace D'
# alt-shift-e = 'move-node-to-workspace E'
# alt-shift-f = 'move-node-to-workspace F'
# alt-shift-g = 'move-node-to-workspace G'
# alt-shift-i = 'move-node-to-workspace I'
# alt-shift-m = 'move-node-to-workspace M'
# alt-shift-n = 'move-node-to-workspace N'
# alt-shift-o = 'move-node-to-workspace O'
# alt-shift-p = 'move-node-to-workspace P'
# alt-shift-q = 'move-node-to-workspace Q'
# alt-shift-r = 'move-node-to-workspace R'
# alt-shift-s = 'move-node-to-workspace S'
# alt-shift-t = 'move-node-to-workspace T'
# alt-shift-u = 'move-node-to-workspace U'
# alt-shift-v = 'move-node-to-workspace V'
# alt-shift-w = 'move-node-to-workspace W'
# alt-shift-x = 'move-node-to-workspace X'
# alt-shift-y = 'move-node-to-workspace Y'
# alt-shift-z = 'move-node-to-workspace Z'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#move-workspace-to-display
alt-shift-tab = 'move-workspace-to-display next'

# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/commands.md#mode
alt-shift-semicolon = 'mode service'
alt-shift-slash = 'mode join'

# It's a declaration of binding mode. See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#bindings-modes
[mode.service.binding]
r = ['flatten-workspace-tree', 'mode main']
o = ['reload-config', 'mode main']
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
esc = 'mode main'
enter = 'mode main'

# It's a declaration of binding mode. See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#bindings-modes
[mode.join.binding]
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
esc = ['reload-config', 'mode main']
enter = 'mode main'
