abbr k 'kubectl'
abbr tf 'terraform'
abbr cx 'chmod +x'
abbr c 'clear'
abbr cls 'clear'
abbr cat 'bat'
abbr cp 'cp -Riv'
abbr g 'git'
abbr ga 'git add'
abbr gaa 'git add --all'
abbr gap 'git apply'
abbr gapa 'git add --patch'
abbr gau 'git add --update'
abbr gb 'git branch -vv'
abbr gbD 'git branch -D'
abbr gba 'git branch -a -v'
abbr gban 'git branch -a -v --no-merged'
abbr gbd 'git branch -d'
abbr gbl 'git blame -b -w'
abbr gbs 'git bisect'
abbr gbsb 'git bisect bad'
abbr gbsg 'git bisect good'
abbr gbsr 'git bisect reset'
abbr gbss 'git bisect start'
abbr gc 'git commit -v'
abbr gca 'git commit -v -a'
abbr gcam 'git commit -a -m'
abbr gcav 'git commit -a -v --no-verify'
abbr gcb 'git checkout -b'
abbr gcf 'git config --list'
abbr gcfx 'git commit --fixup'
abbr gcl 'git clone'
abbr gclean 'git clean -di'
abbr gcm 'git commit -m'
abbr gco 'git_checkout'
abbr gcod 'git checkout develop'
abbr gcom 'git checkout (__git.default_branch)'
abbr gcount 'git shortlog -sn'
abbr gcp 'git cherry-pick'
abbr gcpa 'git cherry-pick --abort'
abbr gcpc 'git cherry-pick --continue'
abbr gcv 'git commit -v --no-verify'
abbr gd 'git diff'
abbr gdca 'git diff --cached'
abbr gds 'git diff --stat'
abbr gdsc 'git diff --stat --cached'
abbr gdto 'git difftool'
abbr gdw 'git diff --word-diff'
abbr gdwc 'git diff --word-diff --cached'
abbr gf 'git fetch'
abbr gfa 'git fetch --all --prune'
abbr gfb 'git flow bugfix'
abbr gfbs 'git flow bugfix start'
abbr gfbt 'git flow bugfix track'
abbr gff 'git flow feature'
abbr gffs 'git flow feature start'
abbr gfft 'git flow feature track'
abbr gfh 'git flow hotfix'
abbr gfhs 'git flow hotfix start'
abbr gfht 'git flow hotfix track'
abbr gfm 'git fetch origin (__git.default_branch) --prune; and git merge FETCH_HEAD'
abbr gfo 'git fetch origin'
abbr gfp 'git flow publish'
abbr gfr 'git flow release'
abbr gfrs 'git flow release start'
abbr gfrt 'git flow release track'
abbr gfs 'git flow support'
abbr gfss 'git flow support start'
abbr gfst 'git flow support track'
abbr gg 'lazygit'
abbr gignore 'git update-index --assume-unchanged'
abbr gl 'git pull'
abbr glg 'git log --stat'
abbr glgg 'git log --graph'
abbr glgga 'git log --graph --decorate --all'
abbr gll 'git pull origin'
abbr glo 'git log --oneline --decorate --color'
abbr glod 'git log --oneline --decorate --color develop..'
abbr glog 'git log --oneline --decorate --color --graph'
abbr gloga 'git log --oneline --decorate --color --graph --all'
abbr glom 'git log --oneline --decorate --color (__git.default_branch)..'
abbr gloo 'git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=short'
abbr glr 'git pull --rebase'
abbr gm 'git merge'
abbr gmom 'git merge origin/(__git.default_branch)'
abbr gmt 'git mergetool --no-prompt'
abbr gp 'git push'
abbr gpo 'git push origin'
abbr gpu 'ggp --set-upstream'
abbr gpv 'git push --no-verify'
abbr gr 'git remote -vv'
abbr gra 'git remote add'
abbr grb 'git rebase'
abbr grba 'git rebase --abort'
abbr grbc 'git rebase --continue'
abbr grbd 'git rebase develop'
abbr grbdi 'git rebase develop --interactive'
abbr grbdia 'git rebase develop --interactive --autosquash'
abbr grbi 'git rebase --interactive'
abbr grbm 'git rebase (__git.default_branch)'
abbr grbmi 'git rebase (__git.default_branch) --interactive'
abbr grbmia 'git rebase (__git.default_branch) --interactive --autosquash'
abbr grbs 'git rebase --skip'
abbr grev 'git revert'
abbr grh 'git reset'
abbr grhh 'git reset --hard'
abbr grhpa 'git reset --patch'
abbr grm 'git rm'
abbr grmc 'git rm --cached'
abbr grmv 'git remote rename'
abbr grpo 'git remote prune origin'
abbr grrm 'git remote remove'
abbr grs 'git restore'
abbr grset 'git remote set-url'
abbr grss 'git restore --source'
abbr grst 'git restore --staged'
abbr grup 'git remote update'
abbr grv 'git remote -v'
abbr gscam 'git commit -S -a -m'
abbr gsd 'git svn dcommit'
abbr gsh 'git show'
abbr gsr 'git svn rebase'
abbr gss 'git status -s'
abbr gst 'git status'
abbr gsta 'git stash'
abbr gstd 'git stash drop'
abbr gstl 'git stash list'
abbr gstp 'git stash pop'
abbr gsts 'git stash show --text'
abbr gsu 'git submodule update'
abbr gsur 'git submodule update --recursive'
abbr gsuri 'git submodule update --recursive --init'
abbr gsw 'git switch'
abbr gswc 'git switch --create'
abbr gts 'git tag -s'
abbr gtv 'git tag'
abbr gunignore 'git update-index --no-assume-unchanged'
abbr gup 'git pull --rebase'
abbr gupa 'git pull --rebase --autostash'
abbr gupav 'git pull --rebase --autostash -v'
abbr gupv 'git pull --rebase -v'
abbr gwch 'git whatchanged -p --abbrev-commit --pretty=medium'
abbr gwt 'git worktree'
abbr gwta 'git worktree add'
abbr gwtlo 'git worktree lock'
abbr gwtls 'git worktree list'
abbr gwtmv 'git worktree move'
abbr gwtpr 'git worktree prune'
abbr gwtrm 'git worktree remove'
abbr gwtulo 'git worktree unlock'
abbr l 'ls -l'
abbr mkdir 'mkdir -vp'
abbr mv 'mv -i'
abbr r 'cd_repo'
abbr rm 'rm -i'
abbr tree 'ls --tree -I "node_modules|.git|dist|out|target|.husky"'
