#!/bin/bash
# Launch the system default browser respecting xdg-settings

browser_desktop=$(xdg-settings get default-web-browser)
browser_exec=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' ~/.local/share/applications/$browser_desktop /usr/share/applications/$browser_desktop 2>/dev/null | head -1)

if [ -z "$browser_exec" ]; then
    # Fallback to qutebrowser if we can't find the desktop file
    browser_exec="qutebrowser"
fi

exec $browser_exec "$@"