[[session]]
name = "scratch"
path = "~"

[[session]]
name = "alon-pc 🖥️"
path = "~"
startup_command = "mosh alon@alon-pc -- sesh picker"

[[session]]
name = "mini"
path = "~"
startup_command = "mosh hearter@mini -- sesh picker"

