[[session]]
name = "scratch"
path = "~"

[[session]]
name = "alon-mbp 💻"
path = "~"
startup_command = "mosh alonhearter@alon-mbp -- sesh picker"

[[session]]
name = "mini"
path = "~"
startup_command = "mosh hearter@mini -- sesh picker"

[[session]]
name = "irssi"
path = "~"
startup_command = "irssi"
