[[session]]
name = "scratch"
path = "~"

[[session]]
name = "alon-mbp 💻"
path = "~"
startup_command = "mosh alonhearter@alon-mbp -- sesh picker"

[[session]]
name = "mini"
path = "~"
startup_command = "mosh hearter@mini -- sesh picker"

[[session]]
name = "media"
path = "~/repos/barlevalon/kielbasa/"
startup_command = "mosh alon@media"

[[session]]
name = "personal"
path = "~/repos/barlevalon/kielbasa/"
startup_command = "mosh alon@personal"

[[session]]
name = "edge"
path = "~/repos/barlevalon/kielbasa/"
startup_command = "mosh alon@edge"

[[session]]
name = "irssi"
path = "~"
startup_command = "irssi"
