# Walker configuration - only overrides from defaults
app_launch_prefix = "uwsm app -- "
terminal = "ghostty"
close_when_open = true
theme = "main"
theme_location = ["~/.config/walker/themes/"]
force_keyboard_focus = true

[builtins.websearch]
prefix = "?"

[[builtins.websearch.entries]]
name = "Kagi"
url = "https://kagi.com/search?q=%TERM%"